version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: stock_picker_db
    environment:
      POSTGRES_USER: stockpicker
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: stock_picker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: stock_picker_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock_picker_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://stockpicker:devpassword@postgres:5432/stock_picker
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock_picker_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

volumes:
  postgres_data:
  redis_data:
